# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Datas\PyQt\proposal_form.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1150, 910)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        MainWindow.setAcceptDrops(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(290, 20, 741, 34))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_timenow = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl_timenow.setMaximumSize(QtCore.QSize(16777215, 16777213))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lbl_timenow.setFont(font)
        self.lbl_timenow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lbl_timenow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_timenow.setText("")
        self.lbl_timenow.setObjectName("lbl_timenow")
        self.horizontalLayout.addWidget(self.lbl_timenow)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lbl_user = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lbl_user.setFont(font)
        self.lbl_user.setObjectName("lbl_user")
        self.horizontalLayout.addWidget(self.lbl_user)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(70, 60, 1021, 761))
        self.stackedWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pps_insert = QtWidgets.QWidget()
        self.pps_insert.setObjectName("pps_insert")
        self.layoutWidget = QtWidgets.QWidget(self.pps_insert)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 60, 871, 58))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"border-radius:3px;\n"
"border:1px solid black;\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.pps_insert)
        self.layoutWidget1.setGeometry(QtCore.QRect(810, 20, 189, 34))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_data_date = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_data_date.setFont(font)
        self.lbl_data_date.setText("")
        self.lbl_data_date.setObjectName("lbl_data_date")
        self.horizontalLayout_2.addWidget(self.lbl_data_date)
        self.lbl_qid = QtWidgets.QLabel(self.layoutWidget1)
        self.lbl_qid.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_qid.setFont(font)
        self.lbl_qid.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_qid.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbl_qid.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_qid.setText("")
        self.lbl_qid.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_qid.setObjectName("lbl_qid")
        self.horizontalLayout_2.addWidget(self.lbl_qid)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.save_btn = QtWidgets.QPushButton(self.pps_insert)
        self.save_btn.setGeometry(QtCore.QRect(890, 730, 91, 31))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_btn.setFont(font)
        self.save_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_btn.setStyleSheet("QPushButton {\n"
"    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);\n"
"    background-color:#f9f9f9;\n"
"    border-radius:6px;\n"
"    border:1px solid #dcdcdc;\n"
"    font-weight:bold;\n"
"    background-color:qlineargradient(spread:pad, x1:0.51, y1:0.05, x2:0.51,             y2:0.95, stop:0 rgba(196, 206, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #e9e9e9 5%, #f9f9f9 100%);\n"
"    background-color:#e9e9e9;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1px solid #6699cc;\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../pyqt/3/PNG/16X16/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon)
        self.save_btn.setFlat(False)
        self.save_btn.setObjectName("save_btn")
        self.layoutWidget_3 = QtWidgets.QWidget(self.pps_insert)
        self.layoutWidget_3.setGeometry(QtCore.QRect(50, 120, 951, 591))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.gridLayout.addWidget(self.plainTextEdit_2, 0, 0, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);\n"
"    background-color:#f9f9f9;\n"
"    border:1px solid #dcdcdc;\n"
"    font-weight:bold;\n"
"    background-color:qlineargradient(spread:pad, x1:0.51, y1:0.05, x2:0.51,             y2:0.95, stop:0 rgba(196, 206, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.gridLayout.addWidget(self.plainTextEdit_4, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);\n"
"    background-color:#f9f9f9;\n"
"    border:1px solid #dcdcdc;\n"
"    font-weight:bold;\n"
"    background-color:qlineargradient(spread:pad, x1:0.51, y1:0.05, x2:0.51,             y2:0.95, stop:0 rgba(196, 206, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.plainTextEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.gridLayout.addWidget(self.plainTextEdit_3, 3, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("QLabel{\n"
"    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);\n"
"    background-color:#f9f9f9;\n"
"    border:1px solid #dcdcdc;\n"
"    font-weight:bold;\n"
"    background-color:qlineargradient(spread:pad, x1:0.51, y1:0.05, x2:0.51,             y2:0.95, stop:0 rgba(196, 206, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Adobe Arabic")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("QLabel{\n"
"    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);\n"
"    background-color:#f9f9f9;\n"
"    border:1px solid #dcdcdc;\n"
"    font-weight:bold;\n"
"    background-color:qlineargradient(spread:pad, x1:0.51, y1:0.05, x2:0.51,             y2:0.95, stop:0 rgba(196, 206, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(self.pps_insert)
        self.layoutWidget2.setGeometry(QtCore.QRect(663, 20, 141, 34))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_writer_name = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(12)
        self.lbl_writer_name.setFont(font)
        self.lbl_writer_name.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lbl_writer_name.setText("")
        self.lbl_writer_name.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_writer_name.setObjectName("lbl_writer_name")
        self.horizontalLayout_3.addWidget(self.lbl_writer_name)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.pps_insert)
        self.label_9.setGeometry(QtCore.QRect(420, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.comboBox = QtWidgets.QComboBox(self.pps_insert)
        self.comboBox.setGeometry(QtCore.QRect(283, 24, 131, 21))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.stackedWidget.addWidget(self.pps_insert)
        self.pps_show = QtWidgets.QWidget()
        self.pps_show.setObjectName("pps_show")
        self.btn_show_my_data = QtWidgets.QPushButton(self.pps_show)
        self.btn_show_my_data.setGeometry(QtCore.QRect(900, 730, 71, 31))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(12)
        self.btn_show_my_data.setFont(font)
        self.btn_show_my_data.setObjectName("btn_show_my_data")
        self.tableWidget = QtWidgets.QTableWidget(self.pps_show)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 980, 670))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.tableWidget.setFont(font)
        self.tableWidget.setMouseTracking(False)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setAcceptDrops(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setProperty("showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setDefaultDropAction(QtCore.Qt.ActionMask)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideNone)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(False)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(180)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.btn_show_all_data = QtWidgets.QPushButton(self.pps_show)
        self.btn_show_all_data.setGeometry(QtCore.QRect(820, 730, 71, 31))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(12)
        self.btn_show_all_data.setFont(font)
        self.btn_show_all_data.setObjectName("btn_show_all_data")
        self.stackedWidget.addWidget(self.pps_show)
        self.btn_page = QtWidgets.QPushButton(self.centralwidget)
        self.btn_page.setGeometry(QtCore.QRect(80, 800, 91, 31))
        font = QtGui.QFont()
        font.setFamily("B Mitra")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_page.setFont(font)
        self.btn_page.setStyleSheet("QPushButton {\n"
"    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);\n"
"    background-color:#f9f9f9;\n"
"    border-radius:4px;\n"
"    border:1px solid #dcdcdc;\n"
"    font-weight:bold;\n"
"    background-color:qlineargradient(spread:pad, x1:0.51, y1:0.05, x2:0.51,             y2:0.95, stop:0 rgba(196, 206, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"QPushButton:hover {\n"
"    background:linear-gradient(to bottom, #e9e9e9 5%, #f9f9f9 100%);\n"
"    background-color:#e9e9e9;\n"
"}\n"
"QPushButton:hover:!pressed\n"
"{\n"
"  border: 1px solid #6699cc;\n"
"}\n"
"")
        self.btn_page.setFlat(False)
        self.btn_page.setObjectName("btn_page")
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.toolBar.setFont(font)
        self.toolBar.setTabletTracking(False)
        self.toolBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.toolBar.setAutoFillBackground(False)
        self.toolBar.setStyleSheet("QToolBar{\n"
"    background:linear-gradient(to bottom, #f9f9f9 5%, #e9e9e9 100%);\n"
"    background-color:#f9f9f9;\n"
"    border:1px solid #dcdcdc;\n"
"    color:#3d3d3d;\n"
"    font-family:Arial;\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"    background-color:qlineargradient(spread:pad, x1:0.51, y1:0.05, x2:0.51,             y2:0.95, stop:0 rgba(196, 206, 207, 255), stop:1 rgba(255, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.toolBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setOrientation(QtCore.Qt.Horizontal)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setStyleSheet("QStatusBar:{\n"
"    color: #2D2D2D !important;\n"
"    background-color: rgb(238, 238, 238);\n"
"    font-weight:bold;\n"
"}\n"
"")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.tlb_cut = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Cut.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_cut.setIcon(icon1)
        self.tlb_cut.setObjectName("tlb_cut")
        self.tlb_copy = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Copy.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_copy.setIcon(icon2)
        self.tlb_copy.setObjectName("tlb_copy")
        self.tlb_paste = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Paste.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_paste.setIcon(icon3)
        self.tlb_paste.setObjectName("tlb_paste")
        self.tlb_delete = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/File Cancel.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_delete.setIcon(icon4)
        self.tlb_delete.setObjectName("tlb_delete")
        self.tlb_exit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../pyqt/exit-icon-4608-Windows.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_exit.setIcon(icon5)
        self.tlb_exit.setObjectName("tlb_exit")
        self.tlb_next = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Rewind.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_next.setIcon(icon6)
        self.tlb_next.setObjectName("tlb_next")
        self.tlb_previous = QtWidgets.QAction(MainWindow)
        self.tlb_previous.setEnabled(True)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Forward.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_previous.setIcon(icon7)
        self.tlb_previous.setObjectName("tlb_previous")
        self.tlb_last = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Skip Forward.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_last.setIcon(icon8)
        self.tlb_last.setObjectName("tlb_last")
        self.tlb_first = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Fast Forward.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_first.setIcon(icon9)
        self.tlb_first.setObjectName("tlb_first")
        self.tlb_print = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Print.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_print.setIcon(icon10)
        self.tlb_print.setObjectName("tlb_print")
        self.tlb_edit = QtWidgets.QAction(MainWindow)
        self.tlb_edit.setEnabled(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Edit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_edit.setIcon(icon11)
        self.tlb_edit.setObjectName("tlb_edit")
        self.tlb_new = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/New.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_new.setIcon(icon12)
        self.tlb_new.setObjectName("tlb_new")
        self.tlb_doc = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../pyqt/1/bonus/icons-shadowless-32/question.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_doc.setIcon(icon13)
        self.tlb_doc.setVisible(True)
        self.tlb_doc.setObjectName("tlb_doc")
        self.tlb_save = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../pyqt/3/ICO/Save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tlb_save.setIcon(icon14)
        self.tlb_save.setObjectName("tlb_save")
        self.toolBar.addAction(self.tlb_new)
        self.toolBar.addAction(self.tlb_delete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.tlb_paste)
        self.toolBar.addAction(self.tlb_copy)
        self.toolBar.addAction(self.tlb_cut)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.tlb_print)
        self.toolBar.addAction(self.tlb_first)
        self.toolBar.addAction(self.tlb_previous)
        self.toolBar.addAction(self.tlb_next)
        self.toolBar.addAction(self.tlb_last)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.tlb_doc)
        self.toolBar.addAction(self.tlb_exit)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.plainTextEdit)
        MainWindow.setTabOrder(self.plainTextEdit, self.plainTextEdit_2)
        MainWindow.setTabOrder(self.plainTextEdit_2, self.plainTextEdit_4)
        MainWindow.setTabOrder(self.plainTextEdit_4, self.plainTextEdit_3)
        MainWindow.setTabOrder(self.plainTextEdit_3, self.save_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "تاریخ:"))
        self.lbl_user.setText(_translate("MainWindow", "علیرضا "))
        self.label_7.setText(_translate("MainWindow", "کاربر:"))
        self.label.setText(_translate("MainWindow", "عنوان پیشنهاد"))
        self.label_10.setText(_translate("MainWindow", "شماره سوال:"))
        self.save_btn.setText(_translate("MainWindow", "ذخیره"))
        self.plainTextEdit.setToolTip(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'B Mitra\',\'Arial\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" dir=\'rtl\' style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "مراحل و اقدامهای مورد نیاز برای اجرای پیشنهاد"))
        self.label_4.setText(_translate("MainWindow", "شرح مزایای وضعیت پیشنهادی"))
        self.label_3.setText(_translate("MainWindow", "شرح وضعیت فعلی و مشکلات آن"))
        self.label_2.setText(_translate("MainWindow", "شرح پیشنهاد"))
        self.label_8.setText(_translate("MainWindow", "نام نویسنده:"))
        self.label_9.setText(_translate("MainWindow", "به کمیته:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "کمیته 1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "کمیته 2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "کمیته 3"))
        self.btn_show_my_data.setText(_translate("MainWindow", "نظرات من"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "شماره"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "شناسه کاربری"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "نام کاربر"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "تاریخ"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "عنوان"))
        self.btn_show_all_data.setText(_translate("MainWindow", "همه نظرات"))
        self.btn_page.setText(_translate("MainWindow", "لیست سوالات"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.tlb_cut.setText(_translate("MainWindow", "برش"))
        self.tlb_cut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.tlb_copy.setText(_translate("MainWindow", "کپی"))
        self.tlb_copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.tlb_paste.setText(_translate("MainWindow", "چسباندن"))
        self.tlb_paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.tlb_delete.setText(_translate("MainWindow", "حذف"))
        self.tlb_exit.setText(_translate("MainWindow", "خروج"))
        self.tlb_next.setText(_translate("MainWindow", "بعدی"))
        self.tlb_previous.setText(_translate("MainWindow", "قبلی"))
        self.tlb_last.setText(_translate("MainWindow", "آخرین"))
        self.tlb_first.setText(_translate("MainWindow", "اولین"))
        self.tlb_print.setText(_translate("MainWindow", "پرینت"))
        self.tlb_edit.setText(_translate("MainWindow", "ویرایش"))
        self.tlb_new.setText(_translate("MainWindow", "جدید"))
        self.tlb_doc.setText(_translate("MainWindow", "راهنما"))
        self.tlb_save.setText(_translate("MainWindow", "ذخیره"))
        self.tlb_save.setShortcut(_translate("MainWindow", "Ctrl+S"))

